### ISSUE TITLE
Can not find command.publishStub function

### ISSUE THREAD

**Issue by felixgani** [tom-brulin/adonis6-amqp#1]
I'm trying your adonis package with adonis 6, I got an error while I try to run
```node ace configure adonis6-amqp```

this's the error message:

```[ error ] command.publishStub is not a function```

Am I need to install something?

**Comment by tom-brulin** [comment]
Hi,

Sorry for late answer.

This package was developped during Adonis 6 alpha, this might be why it's not working anymore.

I'm currently working on a new version of this package that will be more expandable and suitable.
